services:

  # ──────────────────────────────────────────────
  # Database
  # ──────────────────────────────────────────────
  db:
    image: postgres:16.2-alpine
    container_name: project_management_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-project_management}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - pm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-project_management}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: odoo:17.0
    container_name: project_management_web
    restart: always
    command:
      - odoo
      - -d
      - bb_test_db
      - --db_host=db
      - --db_user=admin
      - --db_password=admin123
      - --no-database-list
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./project_addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      - HOST=db
      - USER=admin
      - PASSWORD=admin123
    networks:
      - pm_network


volumes:
  postgres_data:
  opensearch-data:

networks:
  pm_network:
    driver: bridge
  
